### ISSUE TITLE
question about initMN

### ISSUE THREAD

**Issue by MarisaKirisame** [yallop/haskell-frex#1]
initMN :: Ring r ⇒ Int → r
initMN 0 = r₀
initMN 1 = r₁
initMN n | n < 0 = rneg (initMN (-n))
         | odd n     = two ⊗ initMN ((n - 2) `div` 2) ⊕ r₁
         | otherwise = two ⊗ initMN ((n - 2) `div` 2)
  where two = r₁ ⊕ r₁
this look strange to me... can you explain the otherwie case?
If I get it correctly,
initMN 4 = two ⊗ initMN ((4 - 2) `div` 2) = two ⊗ initMN 1 = two ⊗ r₁ = (r₁ ⊕ r₁) ⊗ r₁ = r₁ ⊕ r₁
Is there something wrong?

**Comment by yallop** [comment]
Fixed by #2
